### ISSUE TITLE
GET /heroStats - "hero_id" attribute missing for 121 (GrimStroke) 

### ISSUE THREAD

**Issue by nice** [odota/web#1887]
**Current Behavior**
`hero_id` attribute is missing from the `GET /heroStats` api for `121 (GrimStroke)`. `pro_win`, `pro_pick` and `pro_ban` are also missing which is understandable since hero not in CM.

**Expected behavior/code**
I think it will be a good idea to add `hero_id` for consistent parsing of stats, and also good to set `pro_pick`, `pro_ban` and `pro_win` to `0` for consistency purposes. Thanks

**Comment by howardchung** [comment]
think the fix actually needs to go in odota/core for this, but I agree

**Comment by fcostantini** [comment]
This is fixed already, right? I can see `hero_id` and the pro percentages just fine

**Comment by howardchung** [comment]
I don't think it's fixed for the case where there's 0 games played (e.g. new hero)  it works fine otherwise.

**Comment by suttonau** [comment]
Is anyone currently working on this? I'd like to start working on it if nobody else already working on a solution

**Comment by howardchung** [comment]
I don't believe so, go for it!

**Comment by Javiercerna** [comment]
Is this still an issue? Can I work on this?

**Comment by howardchung** [comment]
yes, although it's not super important. I suspect the SQL queries here need to be modified so that 0 row results are also included in the grouping:
https://github.com/odota/core/blob/master/svc/herostats.js

**Comment by Javiercerna** [comment]
Hi, I'm trying to deploy odota-core locally to make the modifications as you suggested, but it is really difficult in my OS to run docker (Windows 10 Home).

Is there another way to handle this? If not, I'll keep trying to deploy odota-core however I can

**Comment by howardchung** [comment]
You can run a linux VM via virtualbox and develop there.

Alternatively, you can just run postgres, fill the database with some fake data manually and just test the query without running the rest.

**Comment by lancebendo** [comment]
Just made a PR for this issue but it is in odota/core repo. Link [https://github.com/odota/core/pull/1900](url)
